blank_issues_enabled: true
contact_links:
  - name: Discussions/Questions etc
    url: https://github.com/projectmesa/mesa-frames/discussions
    about: Discuss Mesa-Frames, ask questions, do discussions, share ideas, and showcase your projects
